### PR TITLE
Function names and class keyword font and colors

### PR DESCRIPTION
**Pull request by devenv**

### CODE REVIEW

**Comment by dstepanov** [comment]
Class keyword should have the keyword category and fontcolor with default="class", it would be better to not modify default color settings.

If you want to add some highlights you need to use SemanticAnalyzer see an example in the branch syntaxhl.

Also "function arrow" can be "->" and also "=>".

**Comment by devenv** [comment]
About the class keyword - I disagree, it's too confusing when everything is colored in two colors - black and blue...
My problem was that I couldn't see where class or function starts and ends, this way it's instantly visible... I tried to keep it close to conventions, blue, but some sort of destinction is a must IMO...
In other languages you would be 100% right, but coffee is too minimalistic, no brackets etc...

No time to get into SemanticAnalyzer thingy right now, may be some time in the future :)

Added => arrow support

**Comment by dstepanov** [comment]
The class keyword font and colors should be default by the IDE (there could be different themes), but there should be an ability to change it, so default values: "class" should be blue like a keyword and "arrow" should be black like an operator. Right now it isn't posible to change but if you add specific token it should be possible.

I don't really understand what are you trying to highlight in a function definition, I can see associated variable or property is blue but sometimes brackets and some arguments are also blue.

Sorry but I cannot merge function highlighting. If you change "arrow" and "class" to have default colors with ability to change it in the setting I would merge that change.

**Comment by devenv** [comment]
It highlights the function name and it's brackets...
Done the default values :)

**Pull request closed without merging**
